<?php

/**
 * Created by IntelliJ IDEA.
 * User: Max Sky
 * Date: 2024/04/26
 * Time: 05:27
 */

namespace ESignClientTests\Sign;

use Carbon\Carbon;
use ESignClientTests\TestCase;
use MaxSky\ESign\Config\ESignConfig;
use MaxSky\ESign\ESignOpenAPI;
use MaxSky\ESign\Exceptions\ESignConfigException;
use MaxSky\ESign\Exceptions\ESignRequestParameterException;
use MaxSky\ESign\Exceptions\ESignResponseException;

class SignFlowTest extends TestCase {

    private $config;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $config = new ESignConfig();
        $config->appId = 'test';
        $config->appSecret = 'test';

        $this->config = $config;
    }

    /**
     * @return void
     * @throws ESignConfigException
     * @throws ESignRequestParameterException
     * @throws ESignResponseException
     */
    public function testQueryOrganizationFlowList() {
        ESignOpenAPI::setConfig($this->config);

        $start = Carbon::createFromDate(2024, 3, 1)->startOfDay()->getTimestampMs();
        $to = Carbon::createFromDate(2024, 3, 31)->endOfDay()->getTimestampMs();

        $response = ESignOpenAPI::signFlow()->queryOrganizationFlowList(1, 10, [
            'signFlowStartTimeFrom' => $start,
            'signFlowStartTimeTo' => $to
        ]);

        $this->assertTrue(!$response->getCode()); // code will return 0 if success
    }
}
