<?php

/**
 * Created by IntelliJ IDEA.
 * User: Max Sky
 * Date: 2024/04/26
 * Time: 02:56
 */

namespace ESignClientTests\Common;

use ESignClientTests\TestCase;
use MaxSky\ESign\Common\ESignUtilHelper;

class ESignUtilTest extends TestCase {

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetContentMd5() {

    }

    public function testGetFileContentMd5() {

    }

    public function testGetSignature() {
        $target = 'MDBQ4PfgttLGiImHPRpdQNxHQjcR5arnW1vb4dYlegk=';

        $appSecret = 'test';
        $contentMd5 = 'test';

        $uri = '/v3/sign-flow/create-by-file?c=1&z=3&m=2&arr[0]=99&arr[1]=88&arr[2]=77';

        $signed = ESignUtilHelper::getSignature($appSecret, 'POST', 'application/json', $contentMd5, null, $uri);

        $this->assertTrue($signed === $target);
    }
}
